### ISSUE TITLE
image id as output

### ISSUE THREAD

**Issue by b4st1en** [sysdiglabs/scan-action#43]
Hello,

Please add the image id as output of this action.

This would allow your customers to be able to use some API based workarround on your backend failure.

Regards

**Comment by tembleking** [comment]
Hello @b4st1en,

Thanks for the great feature request. We don’t plan to expose the image ID directly as an output for now, but you can get the same result with a small workaround in your workflow.

Right after the `docker build` step, you can use `docker inspect` to grab the image ID and set it as an output. This lets you reuse it in later steps, for example when calling APIs.

Here’s an example:

```yaml
jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        id: build_image
        run: |
          docker build -t my-app:latest .

      # --- WORKAROUND: Get Image ID ---
      - name: Get Image ID
        id: image_info
        run: |
          # Replace 'my-app:latest' with your image tag
          IMAGE_ID=$(docker inspect --format='{{.Id}}' my-app:latest)
          echo "Image ID found: $IMAGE_ID"
          echo "image_id=$IMAGE_ID" >> $GITHUB_OUTPUT

      - name: Sysdig Secure Inline Scan
        uses: sysdiglabs/scan-action@v3
        with:
          image-tag: "my-app:latest"
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          # ... other parameters

      - name: Use the Image ID for API calls
        run: |
          echo "The scanned image ID is: ${{ steps.image_info.outputs.image_id }}"
          # Example:
          # curl -H "Authorization: Bearer ${{ secrets.SYSDIG_SECURE_TOKEN }}" \
          #      "https://secure.sysdig.com/api/scanning/v1/images/by_id/${{ steps.image_info.outputs.image_id }}"
```

This should give you the flexibility you need without waiting for a new feature. 🙏
