### ISSUE TITLE
iac scan results not published in the job summary

### ISSUE THREAD

**Issue by prashanthbgoud** [sysdiglabs/scan-action#71]
for below job, scan is ran but it does not add the summary to the job. 

this is only with `mode: iac`, vm mode works well

```
      - name: Scan IaC
        uses: sysdiglabs/scan-action@v5
        with:
            mode: "iac"
            recursive: "true"
            sysdig-secure-token: ${{ secrets.SYSDIG_TOKEN }}
            sysdig-secure-url: "https://app.<region>.sysdig.com"
```
