### ISSUE TITLE
Validate sysdig executable download

### ISSUE THREAD

**Issue by MIJOTHY-V2** [sysdiglabs/scan-action#74]
The [sysdig docs](https://docs.sysdig.com/en/sysdig-secure/install-vulnerability-cli-scanner/) instruct users to verify the shasum of the sysdig binary ahead of `chmod`ding and executing it (per general recommendations of basic hardening). This action does not do the verification step. I think it would be valuable to:
1. Have the action verify the shasum of the downloaded binary version by default (either by `curl`ing for the shasum, or baking it into the action)
2. Allow users to supply a shasum input string to be used for verification of arbitrary versions, to allow for the `cli-scanner-version` input to still function with verification, and to allow users to pin the shasum to a known value for further hardening (vs `curl`ing to obtain a shasum each time). For example
  ```yaml
    - name: Scan infrastructure
      uses: sysdiglabs/scan-action@v5
      with:
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        image-tag: "sysdiglabs/dummy-vuln-app:latest"
        cli-scanner-version: "1.18.0"
        cli-scanner-sha256sum: "aee37c790d0e85d9d4478a24303859ff7e76c952d89449967e799dbec923c865"
  ```
